trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    cd PurelyPet
  displayName: 'Move to PurelyPet folder'

- script: |
    cd PurelyPet
    npm install
  displayName: 'Install npm packages'

- script: |
    cd PurelyPet
    npx cucumber-js --profile cli --config cucumber.js
  displayName: 'Run Cucumber.js'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'PurelyPet/cucumber-report.html'
    ArtifactName: 'CucumberReport'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Report'