trigger:
- main
variables:
  system.debug: 'true'

pool:
  vmImage: 'windows-latest'

steps:
- task: ScreenResolutionUtility@1
  inputs:
    displaySettings: 'specific'
    width: '1920'
    height: '1080'

- task: UseNode@1
  inputs:
    version: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install npm packages'

- script: |
    npx @puppeteer/browsers install chrome@127.0.6533.88
  displayName: 'Install Chrome'

- script: |
    npx cucumber-js --profile cli --config cucumber.js --tags "@SimpleTest"
  displayName: 'Run Cucumber.js'

- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    PathtoPublish: 'cucumber-report.html'
    ArtifactName: 'CucumberReport'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Report'

- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    PathtoPublish: 'logs/log.txt'
    ArtifactName: 'LogFile'
    publishLocation: 'Container'
  displayName: 'Publish Log File'
  
- task: PublishCucumberReport@1
  condition: always()
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: ./reports/
    outputPath: ./reports/
    metadata: |
     {
       "ApplicationUrl": "$(App.Url)"
     }
    name: 'Functional Tests'
    title: API
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'reports/report.xml'
  
